services:
  morphson-app:
    build:
      context: ./morphson-app
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./morphson-app/.env
    volumes:
      - ./morphson-app:/home/app
      - /home/app/node_modules
    networks:
      - morphson-net
    depends_on:
      - morphson-api
    stdin_open: true
    tty: true

  morphson-api:
    build:
      context: ./morphson-api
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - ./morphson-api/.env
    volumes:
      - ./morphson-api:/home/app
      - /home/app/node_modules
    networks:
      - morphson-net
    depends_on:
      morphson-db:
        condition: service_healthy

  morphson-db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - morphson-net

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      morphson-db:
        condition: service_healthy
    networks:
      - morphson-net

volumes:
  db-data:
    driver: local

networks:
  morphson-net:
    driver: bridge
