services:
  client:
    build:
      context: ./json-client
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./json-client/.env.development
    volumes:
      - ./json-client:/home/app
      - /home/app/node_modules
    networks:
      - net-json-transformer
    depends_on:
      - api
    tty: true

  api:
    build:
      context: ./json-api
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./json-api/.env.development
    volumes:
      - ./json-api/src:/home/app/src
    networks:
      - net-json-transformer
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: jsondb
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - net-json-transformer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d jsondb"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - net-json-transformer
    depends_on:
      db:
        condition: service_healthy

networks:
  net-json-transformer:
    name: net-json-transformer
