FROM node:20-bullseye

WORKDIR /home/app

RUN apt-get update \
    && apt-get install -y openssl \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json yarn.lock* ./
RUN yarn install

COPY . .

RUN npx prisma generate

CMD ["yarn", "dev"]
