FROM node:20-bullseye

WORKDIR /home/app

RUN apt-get update \
    && apt-get install -y openssl \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json package-lock.json* ./
RUN npm install

COPY . .

RUN npx prisma generate

CMD ["npm", "run", "dev"]
